country_names_map = {
    "albania": "ALB",
    "armenia": "ARM",
    "azerbaijan": "AZE",
    "belarus": "BLR",
    "bosnia and herzegovina": "BIH",
    "bulgaria": "BGR",
    "croatia": "HRV",
    "czech republic": "CZE",
    "estonia": "EST",
    "georgia": "GEO",
    "hungary": "HUN",
    "kazakhstan": "KAZ",
    "kyrgyzstan": "KGZ",
    "latvia": "LVA",
    "lithuania": "LTU",
    "moldova": "MDA",
    "montenegro": "MNE",
    "poland": "POL",
    "romania": "ROU",
    "russian federation": "RUS",
    "serbia": "SRB",
    "slovakia": "SVK",
    "slovenia": "SVN",
    "tajikistan": "TJK",
    "the former yugoslav republic of macedonia": "MKD",
    "turkmenistan": "TKM",
    "ukraine": "UKR",
    "uzbekistan": "UZB",
}
